apiVersion: 1

datasources:
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: Correlation ID
          matcherRegex: 'correlation_id[=:"]+([a-f0-9-]+)'
          url: '$${__value.raw}'
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        tags: [{ key: "service.name", value: "service" }]
        filterByTraceID: true
        filterBySpanID: false
